export const routeLoaders = {
  tours: () => import('@/pages/Tours'),
  tourDetails: () => import('@/pages/TourDetails'),
  packageDetails: () => import('@/pages/PackageDetails'),
  dashboard: () => import('@/pages/Dashboard'),
  adminDashboard: () => import('@/pages/AdminDashboard'),
  guides: () => import('@/pages/Guides'),
  agencies: () => import('@/pages/Agencies'),
  guideDetails: () => import('@/pages/GuideDetails'),
  agencyProfile: () => import('@/pages/AgencyProfile'),
  tripRequest: () => import('@/pages/DirectTripRequestPage'),
  aiAssistant: () => import('@/pages/AIAssistant'),
  about: () => import('@/pages/About'),
  blog: () => import('@/pages/Blog'),
  articleDetails: () => import('@/pages/ArticleDetails'),
  chat: () => import('@/pages/Chat'),
  profile: () => import('@/pages/profile/ProfilePage'),
  settings: () => import('@/pages/profile/SettingsPage'),
  requests: () => import('@/pages/profile/RequestsPage'),
  city: () => import('@/pages/CityPage'),
  findJobs: () => import('@/pages/FindJobs'),
  myTrips: () => import('@/pages/MyTripRequests'),
  requestDetails: () => import('@/pages/profile/RequestDetailPage'),
  signup: () => import('@/pages/Signup'),
  login: () => import('@/pages/Login'),
  destinations: () => import('@/pages/Destinations'),
  search: () => import('@/pages/Search'),
  guideOnboarding: () => import('@/pages/GuideOnboarding'),
};

// Most-specific matchers come first so detail links preload the detail chunk,
// not just their parent listing chunk.
const pathLoaders = [
  [(path) => path.startsWith('/profile/requests/'), routeLoaders.requestDetails],
  [(path) => path === '/profile/requests', routeLoaders.requests],
  [(path) => path === '/profile/settings', routeLoaders.settings],
  [(path) => path === '/profile', routeLoaders.profile],
  [(path) => path.startsWith('/tours/'), routeLoaders.tourDetails],
  [(path) => path === '/tours', routeLoaders.tours],
  [(path) => path.startsWith('/package/'), routeLoaders.packageDetails],
  [(path) => path.startsWith('/guides/'), routeLoaders.guideDetails],
  [(path) => path === '/guides', routeLoaders.guides],
  [(path) => path.startsWith('/agencies/'), routeLoaders.agencyProfile],
  [(path) => path === '/agencies', routeLoaders.agencies],
  [(path) => path.startsWith('/request-trip/'), routeLoaders.tripRequest],
  [(path) => path.startsWith('/blog/'), routeLoaders.articleDetails],
  [(path) => path === '/blog', routeLoaders.blog],
  [(path) => path.startsWith('/destinations/'), routeLoaders.city],
  [(path) => path.startsWith('/chat/'), routeLoaders.chat],
  [(path) => path === '/find-jobs', routeLoaders.findJobs],
  [(path) => path === '/my-trips', routeLoaders.myTrips],
  [(path) => path === '/about', routeLoaders.about],
  [(path) => path === '/ai-assistant', routeLoaders.aiAssistant],
  [(path) => path === '/dashboard' || path.startsWith('/dashboard/'), routeLoaders.dashboard],
  [(path) => path === '/admin', routeLoaders.adminDashboard],
  [(path) => path === '/trip-requests', routeLoaders.requests],
  [(path) => path === '/guide-onboarding', routeLoaders.guideOnboarding],
  [(path) => path === '/login', routeLoaders.login],
  [(path) => path === '/signup' || path === '/register', routeLoaders.signup],
];

export function preloadRoute(path) {
  const match = pathLoaders.find(([matches]) => matches(path));
  const loader = match?.[1];
  if (typeof loader === 'function') void loader();
}
