-- Editable homepage destinations and captions for tour gallery images.

ALTER TABLE public.tours
  ADD COLUMN IF NOT EXISTS gallery_captions JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS main_image_caption TEXT;

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.homepage_destinations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  image_url TEXT NOT NULL,
  name_en TEXT NOT NULL,
  name_fa TEXT,
  name_ar TEXT,
  category_en TEXT,
  category_fa TEXT,
  category_ar TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.homepage_destinations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Homepage destinations are publicly readable" ON public.homepage_destinations;
CREATE POLICY "Homepage destinations are publicly readable"
  ON public.homepage_destinations FOR SELECT
  TO anon, authenticated
  USING (is_active OR EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = (SELECT auth.uid())
      AND (profiles.is_admin = true OR profiles.role = 'admin')
  ));

DROP POLICY IF EXISTS "Admins manage homepage destinations" ON public.homepage_destinations;
CREATE POLICY "Admins manage homepage destinations"
  ON public.homepage_destinations FOR ALL
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = (SELECT auth.uid())
      AND (profiles.is_admin = true OR profiles.role = 'admin')
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = (SELECT auth.uid())
      AND (profiles.is_admin = true OR profiles.role = 'admin')
  ));

GRANT SELECT ON public.homepage_destinations TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.homepage_destinations TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.homepage_destinations_id_seq TO authenticated;
