-- Canonicalize active features that previously existed only as unversioned/manual SQL.

-- 1) Custom AI trip drafts used by TripBuilder.
CREATE TABLE IF NOT EXISTS public.custom_trips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trip_data jsonb NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT custom_trips_status_check CHECK (status IN ('draft','saved','booked','completed'))
);

CREATE INDEX IF NOT EXISTS idx_custom_trips_user_id ON public.custom_trips(user_id);
CREATE INDEX IF NOT EXISTS idx_custom_trips_status ON public.custom_trips(status);
CREATE INDEX IF NOT EXISTS idx_custom_trips_created_at ON public.custom_trips(created_at DESC);

ALTER TABLE public.custom_trips ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "custom_trips_select_own" ON public.custom_trips;
DROP POLICY IF EXISTS "custom_trips_insert_own" ON public.custom_trips;
DROP POLICY IF EXISTS "custom_trips_update_own" ON public.custom_trips;
DROP POLICY IF EXISTS "custom_trips_delete_own" ON public.custom_trips;
DROP POLICY IF EXISTS "Users can view their own trips" ON public.custom_trips;
DROP POLICY IF EXISTS "Users can create their own trips" ON public.custom_trips;
DROP POLICY IF EXISTS "Users can update their own trips" ON public.custom_trips;
DROP POLICY IF EXISTS "Users can delete their own trips" ON public.custom_trips;

CREATE POLICY "custom_trips_select_own"
  ON public.custom_trips FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()));
CREATE POLICY "custom_trips_insert_own"
  ON public.custom_trips FOR INSERT TO authenticated
  WITH CHECK (user_id = (SELECT auth.uid()));
CREATE POLICY "custom_trips_update_own"
  ON public.custom_trips FOR UPDATE TO authenticated
  USING (user_id = (SELECT auth.uid()))
  WITH CHECK (user_id = (SELECT auth.uid()));
CREATE POLICY "custom_trips_delete_own"
  ON public.custom_trips FOR DELETE TO authenticated
  USING (user_id = (SELECT auth.uid()));

REVOKE ALL ON TABLE public.custom_trips FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.custom_trips TO authenticated;

DROP TRIGGER IF EXISTS trg_custom_trips_updated_at ON public.custom_trips;
CREATE TRIGGER trg_custom_trips_updated_at
  BEFORE UPDATE ON public.custom_trips
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 2) Homepage destination editor + tour gallery captions.
ALTER TABLE public.tours
  ADD COLUMN IF NOT EXISTS gallery_captions jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS main_image_caption text;

CREATE TABLE IF NOT EXISTS public.homepage_destinations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  image_url text NOT NULL,
  name_en text NOT NULL,
  name_fa text,
  name_ar text,
  category_en text,
  category_fa text,
  category_ar text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_homepage_destinations_sort_order
  ON public.homepage_destinations(sort_order);
CREATE INDEX IF NOT EXISTS idx_homepage_destinations_active_sort
  ON public.homepage_destinations(is_active, sort_order);

ALTER TABLE public.homepage_destinations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Homepage destinations are publicly readable" ON public.homepage_destinations;
DROP POLICY IF EXISTS "Admins manage homepage destinations" ON public.homepage_destinations;
DROP POLICY IF EXISTS "homepage_destinations_public_active" ON public.homepage_destinations;
DROP POLICY IF EXISTS "homepage_destinations_admin_all" ON public.homepage_destinations;

CREATE POLICY "homepage_destinations_public_active"
  ON public.homepage_destinations FOR SELECT TO anon, authenticated
  USING (is_active IS TRUE);

CREATE POLICY "homepage_destinations_admin_all"
  ON public.homepage_destinations FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND (p.is_admin IS TRUE OR p.role = 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND (p.is_admin IS TRUE OR p.role = 'admin')
    )
  );

GRANT SELECT ON TABLE public.homepage_destinations TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE public.homepage_destinations TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.homepage_destinations_id_seq TO authenticated;

DROP TRIGGER IF EXISTS trg_homepage_destinations_updated_at ON public.homepage_destinations;
CREATE TRIGGER trg_homepage_destinations_updated_at
  BEFORE UPDATE ON public.homepage_destinations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 3) Canonical proposal rejection RPC for the tourist/request owner.
CREATE OR REPLACE FUNCTION public.reject_trip_proposal(proposal_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF (SELECT auth.uid()) IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.trip_slots AS slot
    JOIN public.trip_requests AS request
      ON request.id = slot.trip_request_id
    WHERE slot.id = proposal_id
      AND request.user_id = (SELECT auth.uid())
      AND slot.status NOT IN ('rejected', 'finalized', 'selected', 'closed')
  ) THEN
    RAISE EXCEPTION 'Not authorized to reject this proposal';
  END IF;

  UPDATE public.trip_slots AS slot
  SET status = 'rejected'
  WHERE slot.id = proposal_id
    AND slot.status NOT IN ('rejected', 'finalized', 'selected', 'closed');

  RETURN FOUND;
END;
$$;

REVOKE ALL ON FUNCTION public.reject_trip_proposal(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reject_trip_proposal(uuid) TO authenticated;

NOTIFY pgrst, 'reload schema';
